version: '3.9'

services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: lek0212
      MYSQL_DATABASE: workpermit
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - workpermit_data:/var/lib/mysql  # Define a volume for MySQL data persistence

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: lek0212
    ports:
      - '8081:80'
    networks:
      - mynetwork
    depends_on:
      - db

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: lek0212
      DB_DATABASE: workpermit
      JWT_SECRET: TxjRjKPoOoXGpt12WfuchOjMcb5Th44bcS7b8lk4YmAkecECzWI6VfI6HWsMrrW3
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  workpermit_data:
    driver: local
